parameters:
    database_driver:   pdo_mysql
    database_host:     _DATABASE_HOST
    database_port:     _DATABASE_PORT
    database_name:     _DATABASE_NAME
    database_user:     _DATABASE_USER
    database_password: _DATABASE_PASS

    mailer_address:    ~
    mailer_transport:  gmail
    mailer_host:       ~
    mailer_user:       ~
    mailer_password:   ~

    locale:            __LOCALE__
    secret:            __SECRET__

    app_author:       __AUTHOR__
    app_title:        __TITLE__
    app_description:  __DESC__
    app_theme:         ~

    loopschema_minimum_aantal_lopers:       __WALKERS__
    loopschema_maanden_vooruit:             __MONTHS__
    loopschema_resultaat_voor_lopers:       __RESULT__
