parameters:
    database_driver:   pdo_mysql
    database_host:     _DATABASE_HOST
    database_port:     _DATABASE_PORT
    database_name:     _DATABASE_NAME
    database_user:     _DATABASE_USER
    database_password: _DATABASE_PASS

    mailer_address:    ~
    mailer_transport:  gmail
    mailer_host:       ~
    mailer_user:       ~
    mailer_password:   ~

    locale:            nl
    secret:            SecretTokenForApplication

    app_author:       'Buurtpreventie'
    app_title:        'Buurtpreventie'
    app_description:  'Buurtpreventie in Eindhoven'
    app_theme:         ~

    loopschema_minimum_aantal_lopers:       2
    loopschema_maanden_vooruit:             3
    loopschema_resultaat_voor_lopers:       true
